In [1]:
import numpy as np

In [2]:
A = np.array([
    [1.0, 2.0, 1.0],
    [3.0, 8.0, 1.0],
    [0.0, 4.0, 1.0]
])
print(A)

[[1. 2. 1.]
 [3. 8. 1.]
 [0. 4. 1.]]


In [3]:
E21 = np.eye(3)

multiplier = A[1, 0] / A[0, 0]

In [5]:
E21[1, 0] = -multiplier

print("Constructed Elementary Matrix E21:\n", E21)

Constructed Elementary Matrix E21:
 [[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
A_after_E21 = E21 @ A

print("Result of E21 @ A :\n", A_after_E21)

Result of E21 @ A :
 [[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  4.  1.]]
