In [1]:
import numpy as np

In [9]:
def gaussian_elimination(A_matrix, b_vector):
    A = A_matrix.copy().astype(float)
    b = b_vector.copy().astype(float)
    n = len(b)
    
    for i in range(n):
        pivot = A[i, i]
        
        for j in range(i + 1, n):
            multiplier = A[j, i] / pivot
            
            A[j] = A[j] - multiplier * A[i]
            b[j] = b[j] - multiplier * b[i]

    print("Upper Triangular Matrix U:\n", A)
    print("\nTransformed Vector c:\n", b)
    
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_knowns = np.dot(A[i, i+1:], x[i+1:])
        x[i] = (b[i] - sum_knowns) / A[i, i]
        
    return x

In [10]:
A_input = np.array([
    [1, 2, 1],
    [3, 8, 1],
    [0, 4, 1]
])

b_input = np.array([2, 12, 2])

solution = gaussian_elimination(A_input, b_input)
print("Final Solution vector x (x, y, z):\n", solution)

Upper Triangular Matrix U:
 [[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]

Transformed Vector c:
 [  2.   6. -10.]
Final Solution vector x (x, y, z):
 [ 2.  1. -2.]
