In [1]:
import numpy as np

In [2]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

In [3]:
p = np.array([2, 3, 1])

In [4]:
B = np.column_stack([e1, e2, e3])

print(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
coords_in_B = np.linalg.solve(B, p)

print(coords_in_B)

[2. 3. 1.]
